"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EOperatorTypes = void 0;
var EOperatorTypes;
(function (EOperatorTypes) {
    EOperatorTypes[EOperatorTypes["EqualTo"] = 1] = "EqualTo";
    EOperatorTypes[EOperatorTypes["GreaterOrEqualTo"] = 2] = "GreaterOrEqualTo";
    EOperatorTypes[EOperatorTypes["LessOrEqualTo"] = 3] = "LessOrEqualTo";
    EOperatorTypes[EOperatorTypes["GreaterThan"] = 4] = "GreaterThan";
    EOperatorTypes[EOperatorTypes["LessThan"] = 5] = "LessThan";
    EOperatorTypes[EOperatorTypes["ContainsText"] = 6] = "ContainsText";
    EOperatorTypes[EOperatorTypes["NotEqualTo"] = 7] = "NotEqualTo";
    EOperatorTypes[EOperatorTypes["Empty"] = 8] = "Empty";
    EOperatorTypes[EOperatorTypes["NotEmpty"] = 9] = "NotEmpty";
    EOperatorTypes[EOperatorTypes["StartsWith"] = 10] = "StartsWith";
    EOperatorTypes[EOperatorTypes["DoesNotContainText"] = 11] = "DoesNotContainText";
    EOperatorTypes[EOperatorTypes["DoesNotStartWith"] = 12] = "DoesNotStartWith";
    EOperatorTypes[EOperatorTypes["EndsWith"] = 13] = "EndsWith";
    EOperatorTypes[EOperatorTypes["DoesNotEndWith"] = 14] = "DoesNotEndWith";
    EOperatorTypes[EOperatorTypes["QuickFilter"] = 15] = "QuickFilter";
})(EOperatorTypes = exports.EOperatorTypes || (exports.EOperatorTypes = {}));
